name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make ci
        env:
          REGISTRY: ci
      - name: Smoke test alpine:edge
        run: docker run --rm ci/alpine:edge echo 'OK'
      - name: Smoke test alpine:3.13
        run: docker run --rm ci/alpine:3.13 echo 'OK'
