name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make ci
        env:
          REGISTRY: ci
      - name: Smoke test alpine:edge
        run: docker run --rm ci/alpine:edge echo 'OK'
      - name: Smoke test alpine:3.13
        run: docker run --rm ci/alpine:3.13 echo 'OK'
      - name: Smoke test chromium:latest
        run: docker run --rm ci/chromium:latest --version
      - name: Smoke test chromium-test:latest
        run: docker run --rm ci/chromium-test:latest --version
      - name: Smoke test firefox:latest
        run: docker run --rm ci/firefox:latest --version
      - name: Smoke test gcloud:latest
        run: docker run --rm ci/gcloud:latest gcloud --version
      - name: Smoke test midori:latest
        run: docker run --rm ci/midori:latest --version
      - name: Smoke test net-block:latest
        run: docker run --rm ci/net-block:latest /usr/sbin/dnsmasq --version
      - name: Smoke test net-cache:latest
        run: docker run --rm ci/net-cache:latest /usr/sbin/squid --version
      - name: Smoke test net-tools:latest
        run: docker run --rm ci/net-tools:latest /usr/bin/nmap --version
