# FIXME: check_update.sh results in images only being published when there are
# apk package updates but we ALSO need publish when files within a build
# context have changed
#   ↳ Compare hash of current build vs what's on ghcr.io + existing check_update.sh logic

name: publish
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - master
jobs:
  push_to_registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make ci
        env:
          REGISTRY: ghcr.io/maxmilton
