# https://github.com/snyk/actions/
name: Snyk
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '24 18 * * 2'
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make all
    - name: Snyk check docker vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@d1ee3d73c6f24375d0efc597c74570b0cd08a323
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/maxmilton/chromium
        args: --file=Dockerfile
    - name: Snyk check docker vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@d1ee3d73c6f24375d0efc597c74570b0cd08a323
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/maxmilton/firefox
        args: --file=Dockerfile
    - name: Snyk check docker vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@d1ee3d73c6f24375d0efc597c74570b0cd08a323
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/maxmilton/gcloud
        args: --file=Dockerfile
    - name: Snyk check docker vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@d1ee3d73c6f24375d0efc597c74570b0cd08a323
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/maxmilton/net-block
        args: --file=Dockerfile
    - name: Snyk check docker vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@d1ee3d73c6f24375d0efc597c74570b0cd08a323
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/maxmilton/net-cache
        args: --file=Dockerfile
    - name: Snyk check docker vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@d1ee3d73c6f24375d0efc597c74570b0cd08a323
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/maxmilton/net-tools
        args: --file=Dockerfile
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
